name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  files:
    description: 'Input file(s)'
    required: true
    default: |
      README.md
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: check-square
  color: white