name: Github Action doc generator
description: Github Action doc generator
author: jackton1
inputs:
  action:
    description: 'Path to the action.yml file'
    required: false
    default: action.yml
  col_max_width:
    description: 'Max width of a column'
    required: false
    default: '1000'
  col_max_words:
    description: 'Max number of words per line in a column'
    required: false
    default: '5'
  output:
    description: 'Path to the output file'
    required: false
    default: README.md
  input_columns:
    description: 'List of Input columns'
    required: false
  output_columns:
    description: 'List of Output columns'
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        EXTRA_ARGS=""
  
        for input_column in "${{ join(inputs.input_columns, ' ') }}" do
          EXTRA_ARGS="${EXTRA_ARGS} --input-column ${input_column}"
        done
  
        for output_column in "${{ join(inputs.output_columns, ' ') }}" do
          EXTRA_ARGS="${EXTRA_ARGS} --output-column ${output_column}"
        done
        
        if 
  
        curl -sf https://gobinaries.com/github.com/tj-actions/auto-doc | PREFIX=. sh
  
        ./auto-doc --action="${{ inputs.action }}" --output="${{ inputs.output }}" \
          --colMaxWidth="${{ inputs.col_max_width }}" --colMaxWords="${{ inputs.col_max_words }}" \
          ${EXTRA_ARGS} && exit_status=$? || exit_status=$?

        rm -f ./auto-doc
  
        if [[ $exit_status -ne 0 ]]; then
          echo "::warning::Error occurred running auto-doc"
          exit $exit_status;
        fi
      shell: bash

branding:
  icon: file-text
  color: white
