name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  files:
    description: 'Input file(s)'
    required: true
    default: |
      README.md
runs:
  using: 'composite'
  steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: auto-doc
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_FILES: ${{ inputs.files }}
branding:
  icon: file-text
  color: white
