name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  action:
    description: 'action.yml/yaml file'
    required: true
    default: action.yml
  output:
    description: 'Output file'
    required: true
    default: README.md

runs:
  using: 'composite'
  steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-auto-doc-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-auto-doc-

    - run: |
        make run OUTPUT="${INPUT_OUTPUT}" ACTION="${INPUT_ACTION}"
      id: auto-doc
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_ACTION: ${{ inputs.action }}
branding:
  icon: file-text
  color: white
