name: Action auto doc generator
description: Action auto doc generator
author: jackton1
inputs:
  action:
    description: 'Path to the action.yml file'
    required: true
    default: action.yml
  output:
    description: 'Output file'
    required: true
    default: README.md

runs:
  using: 'composite'
  steps:
    - run: |
        make run OUTPUT="${INPUT_OUTPUT}" ACTION="${INPUT_ACTION}"
      id: auto-doc
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_ACTION: ${{ inputs.action }}
branding:
  icon: file-text
  color: white
